// vaiaconAcademy — Lernplan-Katalog. Wird von der Landingpage und der Lernplan-Seite gelesen.
window.ACADEMY_PLANS = [
  {
    n: '01', title: 'Grundlagen: KI einordnen', level: 'EINSTIEG', hours: '41 Min',
    nutzen: 'Ab der ersten Woche erledigen Sie Texte, Zusammenfassungen und Recherchen in der halben Zeit — rund 30 Minuten pro Arbeitstag, ohne dass Sie etwas installieren müssen.',
    tile: 'Der Einstieg ohne Fachchinesisch — was die Werkzeuge können, wie Sie sie ansprechen und woran Sie eine falsche Antwort erkennen.',
    lead: 'Bevor wir automatisieren, klären wir das Handwerk: was diese Werkzeuge heute wirklich leisten, wie man sie anspricht, woran Sie eine erfundene Antwort erkennen und wie Sie eine Routine aufbauen, die eine Woche später noch steht.',
    bild: 'Bild: Inhaber am Laptop im Betrieb',
    img: 'assets/lernplan-01.png',
    takeaways: ['Prompt-Karte A5', 'Startanleitung Schritt für Schritt', '30-Minuten-Wochenplan', 'Vergleich der gängigen Assistenten', 'Prüfliste gegen erfundene Antworten'],
    lessons: [
      ['Was KI heute kann — und was nicht', 'VIDEO', '3 Min'],
      ['Welcher Assistent für welchen Zweck', 'VIDEO', '3 Min'],
      ['Das erste Gespräch mit einem Assistenten', 'WERKSTATT', '5 Min', {
        absaetze: [
          'Ein KI-Assistent ist kein Suchfeld. Sie schreiben ihm wie einem neuen Mitarbeiter am ersten Tag: schnell und belesen, aber ohne jede Kenntnis Ihres Betriebs. Was er wissen muss, muss im Text stehen.',
          'Fangen Sie mit einer echten Aufgabe von heute an, nicht mit einem Testsatz. Eine Kundenantwort, die Sie ohnehin schreiben müssten, zeigt Ihnen mehr als jedes Kursbeispiel.',
        ],
        punkte: [
          'Schreiben Sie in ganzen Sätzen, nicht in Stichworten.',
          'Sagen Sie, für wen der Text ist und wie lang er werden soll.',
          'Antwortet er daneben, schreiben Sie zurück, was fehlt — statt neu anzufangen.',
          'Kundennamen und Adressen lassen Sie vorerst weg. Warum, steht in Lernplan 02.',
        ],
        uebung: 'Nehmen Sie eine E-Mail, die heute ohnehin ansteht, und lassen Sie sich einen Entwurf schreiben. Vergleichen Sie ihn mit dem, was Sie selbst geschrieben hätten.',
      }],
      ['Gute Anweisungen: die vier Bausteine', 'WERKSTATT', '7 Min', {
        absaetze: [
          'Eine gute Anweisung hat vier Teile. Fehlt einer, rät das Werkzeug — und raten heisst hier: irgendetwas Plausibles.',
          'Der vierte Baustein wirkt am stärksten. Ein einziges echtes Beispiel aus Ihrem Betrieb bringt mehr als drei Absätze Erklärung.',
        ],
        punkte: [
          'Rolle: «Sie sind Sachbearbeiterin in einem Schweizer Malerbetrieb.»',
          'Aufgabe: was genau entstehen soll, in einem Satz.',
          'Rahmen: Länge, Ton, Sprache — und was nicht vorkommen darf.',
          'Beispiel: ein Text von Ihnen, an dem sich der Assistent ausrichtet.',
        ],
        uebung: 'Bauen Sie eine Anweisung mit allen vier Teilen für eine Aufgabe, die bei Ihnen wöchentlich anfällt. Heben Sie sie auf — daraus wird Ihre Prompt-Karte.',
      }],
      ['Wenn der Assistent Unsinn erzählt', 'WERKSTATT', '6 Min', {
        absaetze: [
          'Diese Werkzeuge sagen nie «ich weiss es nicht». Sie erzeugen den wahrscheinlichsten nächsten Satz, und der klingt auch dann souverän, wenn er falsch ist. Das ist keine Panne, sondern die Bauart.',
          'Heikel wird es bei Zahlen, Namen, Paragraphen und Fristen — also genau dort, wo es im Betrieb zählt.',
        ],
        punkte: [
          'Alles, was zitiert wird, prüfen Sie an der Quelle. Nicht beim Assistenten nachfragen.',
          'Je genauer eine Zahl klingt, desto misstrauischer sollten Sie sein.',
          'Fragen Sie dieselbe Sache zweimal in getrennten Gesprächen. Weichen die Antworten ab, ist mindestens eine erfunden.',
          'Fehlt eine Quelle, gilt die Aussage als unbelegt — nicht als richtig.',
        ],
        uebung: 'Lassen Sie sich drei Angaben zu Ihrer Branche nennen und prüfen Sie jede einzelne nach. Notieren Sie, wie viele gestimmt haben.',
      }],
      ['Eigene Dokumente befragen', 'WERKSTATT', '6 Min', {
        absaetze: [
          'Richtig nützlich wird es, wenn der Assistent mit Ihren Unterlagen arbeitet statt mit Weltwissen: Offerten, Protokolle, Leistungsbeschriebe, Handbücher.',
          'Sie legen ein Dokument bei und stellen Fragen dazu. Die Antworten stützen sich dann auf den Text statt auf Vermutungen — sofern Sie das ausdrücklich verlangen.',
        ],
        punkte: [
          'Sagen Sie: «Antworte nur aus dem beigelegten Dokument. Steht es nicht drin, schreib das.»',
          'Ein Dokument nach dem anderen. Zehn auf einmal verwässern die Antwort.',
          'Lassen Sie sich die Stelle nennen, auf die sich die Antwort stützt.',
          'Vor dem Beilegen: Entfernen Sie unbedingt die persönlichen Daten. Was das genau heisst, steht in Lernplan 02.',
        ],
        uebung: 'Nehmen Sie Ihre letzte Offerte und lassen Sie in fünf Sätzen zusammenfassen, was der Kunde bekommt. Prüfen Sie, ob etwas fehlt.',
      }],
      ['Aus einer guten Antwort eine Vorlage machen', 'WERKSTATT', '6 Min', {
        absaetze: [
          'Die meiste Zeit geht verloren, weil jede Woche dieselbe Anweisung neu formuliert wird. Eine gute Antwort ist ein Zwischenergebnis — die Vorlage ist das Ergebnis.',
        ],
        punkte: [
          'Hat eine Anweisung funktioniert, kopieren Sie sie sofort in eine Datei.',
          'Ersetzen Sie das Konkrete durch Platzhalter: [Kunde], [Datum], [Leistung].',
          'Geben Sie ihr einen Namen, unter dem Sie sie in einem Monat wiederfinden.',
          'Eine Vorlage, die zweimal funktioniert hat, gehört ins Team — nicht in Ihren Kopf.',
        ],
        uebung: 'Legen Sie eine Datei «Prompt-Karte» an und tragen Sie die erste Vorlage ein. Drei bis fünf Stück decken den Alltag der meisten Betriebe ab.',
      }],
      ['Ihr Wochenrhythmus: 30 Minuten, die bleiben', 'ÜBUNG', '5 Min', {
        absaetze: [
          'Der häufigste Grund, warum es nach zwei Wochen wieder einschläft: Es gibt keinen festen Platz im Kalender. Gute Vorsätze verlieren gegen den Alltag.',
          'Dreissig Minuten pro Woche reichen für den Anfang. Wichtiger als die Dauer ist, dass der Termin immer am selben Tag steht.',
        ],
        punkte: [
          'Ein fester Termin, dreissig Minuten, gleicher Wochentag.',
          'Eine Aufgabe pro Woche — die, die Sie diese Woche ohnehin nervt.',
          'Halten Sie fest, was funktioniert hat. Zwei Zeilen genügen.',
          'Nach vier Wochen schauen Sie zurück: Was ist geblieben, was nicht?',
        ],
        uebung: 'Tragen Sie den Termin jetzt für die nächsten vier Wochen ein. Nicht später — jetzt.',
      }],
    ],
  },
  {
    n: '02', title: 'Datenschutz & Sicherheit', level: 'GRUNDLAGE', hours: '26 Min',
    nutzen: 'Sie wissen, welche Kundendaten rein dürfen und welche nie. Eine einzige vermiedene Datenschutzpanne ist teurer als jede Weiterbildung.',
    tile: 'Was rein darf und was nie: revDSG, Anonymisieren, Cloud-Standort.',
    lead: 'Die Lektionen, die vor allen anderen kommen sollten: welche Daten Sie nie eingeben, wie Sie Kundenangaben in zwei Minuten anonymisieren und was das revDSG von Ihrem Betrieb verlangt.',
    bild: 'Bild: Aktenordner und Bildschirm',
    img: 'assets/lernplan-02.png',
    takeaways: ['Merkblatt «nie eingeben»', 'Anonymisierungs-Vorlage', 'Sicherheits-Check auf einer Seite'],
    lessons: [
      ['Was Sie nie eingeben dürfen', 'VIDEO + CHECK', '6 Min'],
      ['revDSG in vier Sätzen', 'VIDEO', '3 Min'],
      ['Kundendaten anonymisieren — schnell und sauber', 'WERKSTATT', '7 Min'],
      ['Auftragsverarbeitung und Cloud-Standort', 'VIDEO', '3 Min'],
      ['Der Sicherheits-Check für Ihren Betrieb', 'ÜBUNG', '7 Min'],
    ],
  },
  {
    n: '03', title: 'Korrespondenz & E-Mail', level: 'PRAXIS', hours: '33 Min',
    nutzen: 'Aus zwei Stunden Postfach am Morgen werden vierzig Minuten — mit Antworten, die klingen wie von Ihnen geschrieben.',
    tile: 'Der Posteingang zuerst — Antworten, die nach Ihnen klingen.',
    lead: 'Wo die meisten Stunden verschwinden: im Postfach. Sie bauen Bausteine für Ihre häufigsten Antworten, lernen den Ton treffen und behalten die heiklen Mails selbst in der Hand.',
    bild: 'Bild: Postfach am Morgen',
    img: 'assets/lernplan-03.png',
    takeaways: ['Ton-Profil Ihres Betriebs', 'Baustein-Set für Standardantworten', 'Leitfaden für heikle Mails'],
    lessons: [
      ['Ihre Zeitfresser im Postfach finden', 'ÜBUNG', '6 Min'],
      ['Mails, die nach Ihnen klingen', 'WERKSTATT', '8 Min'],
      ['Standardantworten als Bausteine', 'WERKSTATT', '7 Min'],
      ['Heikle Mails: Reklamation, Mahnung, Absage', 'WERKSTATT', '7 Min'],
      ['Mehrsprachig antworten (F · I · E)', 'WERKSTATT', '5 Min'],
    ],
  },
  {
    n: '04', title: 'Offerten & Aufträge', level: 'PRAXIS', hours: '35 Min',
    nutzen: 'Eine Offerte in zehn Minuten statt in einer Stunde. Wer am selben Tag offeriert, gewinnt mehr Aufträge.',
    tile: 'Aus fünf Stichworten eine Offerte in Ihrer Struktur.',
    lead: 'Vom Stichwort zur fertigen Offerte — mit Ihren Positionen, Ihrer Preislogik und Ihrem Schlusssatz. Danach folgen Nachfassen und Auftragsbestätigung, damit nichts liegen bleibt.',
    bild: 'Bild: Offerte auf dem Bürotisch',
    img: 'assets/lernplan-04.png',
    takeaways: ['Offerten-Gerüst (Word)', 'Preislogik-Beschrieb', 'Nachfass-Sequenz (3 Mails)'],
    lessons: [
      ['Offerten aus Stichworten', 'WERKSTATT', '8 Min'],
      ['Ihre Preislogik hinterlegen', 'WERKSTATT', '7 Min'],
      ['Leistungsbeschriebe, die überzeugen', 'WERKSTATT', '7 Min'],
      ['Nachfassen ohne Verkaufsdruck', 'WERKSTATT', '7 Min'],
      ['Auftragsbestätigung und Übergabe', 'WERKSTATT', '6 Min'],
    ],
  },
  {
    n: '05', title: 'Buchhaltung & Belege', level: 'PRAXIS', hours: '32 Min',
    nutzen: 'Der Belegstapel fürs Treuhandbüro ist in zwanzig Minuten sortiert — und die Treuhandrechnung sinkt, weil die Rückfragen ausbleiben.',
    tile: 'Belegstapel, Spesen, Mahnwesen — bis zur Übergabe ans Treuhandbüro.',
    lead: 'Der Papierkram, den niemand mag: Belege vorsortieren, Spesen erfassen, Zahlungseingänge prüfen. Am Ende steht ein Monatsabschluss, der eine halbe Stunde dauert statt einen Abend.',
    bild: 'Bild: Belege und Kaffeetasse',
    img: 'assets/lernplan-05.png',
    takeaways: ['Belegübergabe-Checkliste', 'Mahn-Textbausteine', 'Monatsabschluss-Ablauf'],
    lessons: [
      ['Belege vorsortieren fürs Treuhandbüro', 'WERKSTATT', '7 Min'],
      ['Spesen und Quittungen ohne Zettelchaos', 'WERKSTATT', '7 Min'],
      ['Zahlungseingänge und Mahnwesen', 'WERKSTATT', '7 Min'],
      ['Monatsabschluss in einer halben Stunde', 'WERKSTATT', '8 Min'],
      ['Was der Treuhänder von Ihnen braucht', 'VIDEO', '3 Min'],
    ],
  },
  {
    n: '06', title: 'Sitzungen & Dokumentation', level: 'PRAXIS', hours: '25 Min',
    nutzen: 'Das Protokoll ist fertig, bevor alle den Sitzungsraum verlassen haben — inklusive Aufgabenliste mit Namen und Termin.',
    tile: 'Aus Notizen werden Protokolle, Aufgaben und Betriebswissen.',
    lead: 'Sitzungen enden meist mit Notizen, die niemand mehr liest. Hier entstehen daraus Protokolle, Aufgabenlisten mit Termin — und ein Betriebshandbuch, das mitwächst.',
    bild: 'Bild: Sitzungstisch mit Notizblock',
    img: 'assets/lernplan-06.png',
    takeaways: ['Protokoll-Vorlage', 'Aufgaben-Extraktion (Prompt)', 'Gerüst fürs Betriebshandbuch'],
    lessons: [
      ['Sitzungsnotizen zu Protokollen', 'WERKSTATT', '7 Min'],
      ['Aufgaben und Termine herausziehen', 'WERKSTATT', '6 Min'],
      ['Wissen festhalten: das Betriebshandbuch', 'WERKSTATT', '7 Min'],
      ['Ihre Vorlagen-Bibliothek aufbauen', 'ÜBUNG', '5 Min'],
    ],
  },
  {
    n: '07', title: 'Kundengewinnung & Sichtbarkeit', level: 'PRAXIS', hours: '39 Min',
    nutzen: 'Website-Texte und Kundenkontakte in einer Stunde pro Monat, in Ihrer Sprache — statt einem Agenturauftrag über einige Tausend Franken.',
    tile: 'Sichtbar bleiben in Ihrer Sprache — ohne Agentur, ohne Verkaufsdruck.',
    lead: 'Website-Texte, Anfragen, Referenzen und ein Rhythmus, den Sie auch im Frühling halten. Alles in Ihrer Sprache — und mit einer klaren Grenze, was Chefsache bleibt.',
    bild: 'Bild: Handwerker mit Kunde vor Ort',
    img: 'assets/lernplan-07.png',
    takeaways: ['Tonalitäts-Profil', 'Textgerüst für Leistungsseiten', 'Referenz-Anfrage (Vorlage)'],
    lessons: [
      ['Ihre Sprache festhalten: das Tonalitäts-Profil', 'WERKSTATT', '7 Min'],
      ['Website-Texte, die nicht nach KI klingen', 'WERKSTATT', '8 Min'],
      ['Anfragen in drei Minuten qualifizieren', 'WERKSTATT', '7 Min'],
      ['Bewertungen und Referenzen einholen', 'ÜBUNG', '6 Min'],
      ['Ein Rhythmus, den Sie halten können', 'ÜBUNG', '8 Min'],
      ['Was Chefsache bleibt', 'VIDEO', '3 Min'],
    ],
  },
  {
    n: '08', title: 'Kundenservice & vaiaconBot', level: 'PRAXIS', hours: '33 Min',
    nutzen: 'Der vaiaconBot beantwortet die zwanzig häufigsten Fragen rund um die Uhr. Ihr Telefon klingelt deutlich seltener für Auskünfte, die längst auf der Website stehen.',
    tile: 'Ein digitaler Mitarbeiter für die zwanzig häufigsten Fragen.',
    lead: 'Der vaiaconBot beantwortet, was sich täglich wiederholt — und gibt sauber an den Menschen ab, wenn es persönlich wird. Sie bauen ihn in dieser Werkstatt selbst.',
    bild: 'Bild: vaiaconBot am Telefon',
    img: 'assets/vaiacon-buerobot-phone.png',
    takeaways: ['Fragenkatalog (20 Fragen)', 'Übergabe-Regeln an den Menschen', 'Qualitäts-Check zum Mitlesen'],
    lessons: [
      ['Die zwanzig häufigsten Fragen sammeln', 'ÜBUNG', '6 Min'],
      ['Ein vaiaconBot für die häufigen Fragen', 'WERKSTATT', '8 Min'],
      ['Übergabe an den Menschen — sauber geregelt', 'WERKSTATT', '7 Min'],
      ['Telefonnotizen und Rückrufe', 'WERKSTATT', '6 Min'],
      ['Qualität prüfen: mitlesen und nachschärfen', 'ÜBUNG', '6 Min'],
    ],
  },
  {
    n: '09', title: 'Abläufe automatisieren', level: 'FORTGESCHRITTEN', hours: '45 Min',
    nutzen: 'Ein Ablauf, den Sie einmal bauen, arbeitet jede Woche weiter — typisch ein halber Arbeitstag pro Monat, den Sie zurückbekommen.',
    tile: 'Vom einzelnen Handgriff zum verlässlichen Ablauf.',
    lead: 'Für Betriebe, die den ersten Nutzen gesehen haben und jetzt Struktur wollen: beschreiben, bauen, verbinden, prüfen — inklusive Rückfallplan, wenn etwas nicht läuft.',
    bild: 'Bild: Werkstatt-Whiteboard mit Ablauf',
    img: 'assets/lernplan-09.png',
    takeaways: ['Prozess-Steckbrief', 'Ablauf-Bauplan', 'Rückfallplan (eine Seite)'],
    lessons: [
      ['Vom Handgriff zum Prozess: sauber beschreiben', 'WERKSTATT', '8 Min'],
      ['Der erste automatische Ablauf', 'WERKSTATT', '8 Min'],
      ['Verbindungen ohne Programmieren', 'WERKSTATT', '8 Min'],
      ['Daten sauber halten', 'WERKSTATT', '7 Min'],
      ['Wenn es schiefgeht: der Rückfallplan', 'WERKSTATT', '6 Min'],
      ['Aus einem Ablauf zehn machen', 'ÜBUNG', '8 Min'],
    ],
  },
  {
    n: '10', title: 'Zahlen & Entscheide', level: 'FÜHRUNG', hours: '21 Min',
    nutzen: 'Sie rechnen vor dem Kauf, ob sich ein Werkzeug lohnt — und stoppen Abos, die nichts bringen. Das sind schnell einige Hundert Franken im Jahr.',
    tile: 'Rechnen statt hoffen: Kosten, Nutzen, Quartals-Entscheid.',
    lead: 'Was bringt es wirklich? Sie rechnen Ihren eigenen Fall durch, vergleichen Lizenzen und entscheiden pro Quartal, was bleibt und was wieder verschwindet.',
    bild: 'Bild: Notizblock mit Zahlen',
    img: 'assets/lernplan-10.png',
    takeaways: ['Business-Case-Rechner', 'Lizenz-Vergleichsblatt', 'Quartals-Entscheid (Vorlage)'],
    lessons: [
      ['Kosten und Nutzen rechnen', 'ÜBUNG', '8 Min'],
      ['Angebote und Lizenzen vergleichen', 'VIDEO', '3 Min'],
      ['Wann sich Eigenbau lohnt — und wann nicht', 'VIDEO', '3 Min'],
      ['Der Quartals-Entscheid: was bleibt, was fliegt', 'ÜBUNG', '7 Min'],
    ],
  },
  {
    n: '11', title: 'Team & Verantwortung', level: 'FÜHRUNG', hours: '27 Min',
    nutzen: 'Ihre Mitarbeitenden nutzen KI nach klaren Regeln statt heimlich am eigenen Konto. Sie behalten die Kontrolle über Daten und Qualität.',
    tile: 'Regeln, Rollen und der Umgang mit Skepsis im Team.',
    lead: 'KI im Betrieb ist Führungsarbeit. Sie schreiben eine Richtlinie auf einer Seite, klären Rollen und Freigaben und nehmen die Mitarbeitenden mit, statt sie zu überfahren.',
    bild: 'Bild: Team im Pausenraum',
    img: 'assets/lernplan-11.png',
    takeaways: ['KI-Richtlinie auf einer Seite', 'Rollen- und Freigabe-Matrix', 'Schulungsplan fürs Team'],
    lessons: [
      ['Eine KI-Richtlinie auf einer Seite', 'WERKSTATT', '8 Min'],
      ['Mitarbeitende mitnehmen statt überfahren', 'VIDEO', '3 Min'],
      ['Wer darf was? Rollen und Freigaben', 'WERKSTATT', '7 Min'],
      ['Umgang mit Skepsis im Team', 'VIDEO', '3 Min'],
      ['KI-Kompetenz messen: der kleine Check', 'ÜBUNG', '6 Min'],
    ],
  },
  // Modul 12 «Advanced: Wie KI wirklich funktioniert» wurde am 08.09.2026
  // entfernt — es diente nur internen Zwecken. Die Kursseiten liegen weiterhin
  // unter academy/kurs/, sind aus der Academy aber nicht mehr verlinkt.
];
