// vaiaconAcademy — Lernplan-Katalog. Wird von der Landingpage und der Lernplan-Seite gelesen.
window.ACADEMY_PLANS = [
  {
    n: '01', title: 'Grundlagen: KI einordnen', level: 'EINSTIEG', hours: '1 Std 05',
    nutzen: 'Ab der ersten Woche erledigen Sie Texte, Zusammenfassungen und Recherchen in der halben Zeit — rund 30 Minuten pro Arbeitstag, ohne dass Sie etwas installieren müssen.',
    tile: 'Der Einstieg ohne Fachchinesisch — was die Werkzeuge können und wie Sie sie ansprechen.',
    lead: 'Bevor wir automatisieren, klären wir das Handwerk: was diese Werkzeuge heute wirklich leisten, wie man sie anspricht und wie Sie eine Routine aufbauen, die eine Woche später noch steht.',
    bild: 'Bild: Inhaber am Laptop im Betrieb',
    img: 'assets/lernplan-01.png',
    takeaways: ['Prompt-Karte A5', 'Startanleitung Schritt für Schritt', '30-Minuten-Wochenplan'],
    lessons: [
      ['Was KI heute kann — und was nicht', 'VIDEO', '8 Min'],
      ['Das erste Gespräch mit einem Assistenten', 'WERKSTATT', '12 Min'],
      ['Gute Anweisungen: die vier Bausteine', 'WERKSTATT', '18 Min'],
      ['Eigene Dokumente befragen', 'WERKSTATT', '15 Min'],
      ['Ihr Wochenrhythmus: 30 Minuten, die bleiben', 'ÜBUNG', '12 Min'],
    ],
  },
  {
    n: '02', title: 'Datenschutz & Sicherheit', level: 'GRUNDLAGE', hours: '1 Std 15',
    nutzen: 'Sie wissen, welche Kundendaten rein dürfen und welche nie. Eine einzige vermiedene Datenschutzpanne ist teurer als jede Weiterbildung.',
    tile: 'Was rein darf und was nie: revDSG, Anonymisieren, Cloud-Standort.',
    lead: 'Die Lektionen, die vor allen anderen kommen sollten: welche Daten Sie nie eingeben, wie Sie Kundenangaben in zwei Minuten anonymisieren und was das revDSG von Ihrem Betrieb verlangt.',
    bild: 'Bild: Aktenordner und Bildschirm',
    img: 'assets/lernplan-02.png',
    takeaways: ['Merkblatt «nie eingeben»', 'Anonymisierungs-Vorlage', 'Sicherheits-Check auf einer Seite'],
    lessons: [
      ['Was Sie nie eingeben dürfen', 'VIDEO + CHECK', '14 Min'],
      ['revDSG in vier Sätzen', 'VIDEO', '12 Min'],
      ['Kundendaten anonymisieren — schnell und sauber', 'WERKSTATT', '16 Min'],
      ['Auftragsverarbeitung und Cloud-Standort', 'VIDEO', '15 Min'],
      ['Der Sicherheits-Check für Ihren Betrieb', 'ÜBUNG', '18 Min'],
    ],
  },
  {
    n: '03', title: 'Korrespondenz & E-Mail', level: 'PRAXIS', hours: '1 Std 22',
    nutzen: 'Aus zwei Stunden Postfach am Morgen werden vierzig Minuten — mit Antworten, die klingen wie von Ihnen geschrieben.',
    tile: 'Der Posteingang zuerst — Antworten, die nach Ihnen klingen.',
    lead: 'Wo die meisten Stunden verschwinden: im Postfach. Sie bauen Bausteine für Ihre häufigsten Antworten, lernen den Ton treffen und behalten die heiklen Mails selbst in der Hand.',
    bild: 'Bild: Postfach am Morgen',
    img: 'assets/lernplan-03.png',
    takeaways: ['Ton-Profil Ihres Betriebs', 'Baustein-Set für Standardantworten', 'Leitfaden für heikle Mails'],
    lessons: [
      ['Ihre Zeitfresser im Postfach finden', 'ÜBUNG', '15 Min'],
      ['Mails, die nach Ihnen klingen', 'WERKSTATT', '20 Min'],
      ['Standardantworten als Bausteine', 'WERKSTATT', '18 Min'],
      ['Heikle Mails: Reklamation, Mahnung, Absage', 'WERKSTATT', '17 Min'],
      ['Mehrsprachig antworten (F · I · E)', 'WERKSTATT', '12 Min'],
    ],
  },
  {
    n: '04', title: 'Offerten & Aufträge', level: 'PRAXIS', hours: '1 Std 28',
    nutzen: 'Eine Offerte in zehn Minuten statt in einer Stunde. Wer am selben Tag offeriert, gewinnt mehr Aufträge.',
    tile: 'Aus fünf Stichworten eine Offerte in Ihrer Struktur.',
    lead: 'Vom Stichwort zur fertigen Offerte — mit Ihren Positionen, Ihrer Preislogik und Ihrem Schlusssatz. Danach folgen Nachfassen und Auftragsbestätigung, damit nichts liegen bleibt.',
    bild: 'Bild: Offerte auf dem Bürotisch',
    img: 'assets/lernplan-04.png',
    takeaways: ['Offerten-Gerüst (Word)', 'Preislogik-Beschrieb', 'Nachfass-Sequenz (3 Mails)'],
    lessons: [
      ['Offerten aus Stichworten', 'WERKSTATT', '22 Min'],
      ['Ihre Preislogik hinterlegen', 'WERKSTATT', '18 Min'],
      ['Leistungsbeschriebe, die überzeugen', 'WERKSTATT', '16 Min'],
      ['Nachfassen ohne Verkaufsdruck', 'WERKSTATT', '18 Min'],
      ['Auftragsbestätigung und Übergabe', 'WERKSTATT', '14 Min'],
    ],
  },
  {
    n: '05', title: 'Buchhaltung & Belege', level: 'PRAXIS', hours: '1 Std 23',
    nutzen: 'Der Belegstapel fürs Treuhandbüro ist in zwanzig Minuten sortiert — und die Treuhandrechnung sinkt, weil die Rückfragen ausbleiben.',
    tile: 'Belegstapel, Spesen, Mahnwesen — bis zur Übergabe ans Treuhandbüro.',
    lead: 'Der Papierkram, den niemand mag: Belege vorsortieren, Spesen erfassen, Zahlungseingänge prüfen. Am Ende steht ein Monatsabschluss, der eine halbe Stunde dauert statt einen Abend.',
    bild: 'Bild: Belege und Kaffeetasse',
    img: 'assets/lernplan-05.png',
    takeaways: ['Belegübergabe-Checkliste', 'Mahn-Textbausteine', 'Monatsabschluss-Ablauf'],
    lessons: [
      ['Belege vorsortieren fürs Treuhandbüro', 'WERKSTATT', '18 Min'],
      ['Spesen und Quittungen ohne Zettelchaos', 'WERKSTATT', '16 Min'],
      ['Zahlungseingänge und Mahnwesen', 'WERKSTATT', '17 Min'],
      ['Monatsabschluss in einer halben Stunde', 'WERKSTATT', '20 Min'],
      ['Was der Treuhänder von Ihnen braucht', 'VIDEO', '12 Min'],
    ],
  },
  {
    n: '06', title: 'Sitzungen & Dokumentation', level: 'PRAXIS', hours: '1 Std 01',
    nutzen: 'Das Protokoll ist fertig, bevor alle den Sitzungsraum verlassen haben — inklusive Aufgabenliste mit Namen und Termin.',
    tile: 'Aus Notizen werden Protokolle, Aufgaben und Betriebswissen.',
    lead: 'Sitzungen enden meist mit Notizen, die niemand mehr liest. Hier entstehen daraus Protokolle, Aufgabenlisten mit Termin — und ein Betriebshandbuch, das mitwächst.',
    bild: 'Bild: Sitzungstisch mit Notizblock',
    img: 'assets/lernplan-06.png',
    takeaways: ['Protokoll-Vorlage', 'Aufgaben-Extraktion (Prompt)', 'Gerüst fürs Betriebshandbuch'],
    lessons: [
      ['Sitzungsnotizen zu Protokollen', 'WERKSTATT', '16 Min'],
      ['Aufgaben und Termine herausziehen', 'WERKSTATT', '15 Min'],
      ['Wissen festhalten: das Betriebshandbuch', 'WERKSTATT', '18 Min'],
      ['Ihre Vorlagen-Bibliothek aufbauen', 'ÜBUNG', '12 Min'],
    ],
  },
  {
    n: '07', title: 'Kundengewinnung & Sichtbarkeit', level: 'PRAXIS', hours: '1 Std 38',
    nutzen: 'Website-Texte und Kundenkontakte in einer Stunde pro Monat, in Ihrer Sprache — statt einem Agenturauftrag über einige Tausend Franken.',
    tile: 'Sichtbar bleiben in Ihrer Sprache — ohne Agentur, ohne Verkaufsdruck.',
    lead: 'Website-Texte, Anfragen, Referenzen und ein Rhythmus, den Sie auch im Frühling halten. Alles in Ihrer Sprache — und mit einer klaren Grenze, was Chefsache bleibt.',
    bild: 'Bild: Handwerker mit Kunde vor Ort',
    img: 'assets/lernplan-07.png',
    takeaways: ['Tonalitäts-Profil', 'Textgerüst für Leistungsseiten', 'Referenz-Anfrage (Vorlage)'],
    lessons: [
      ['Ihre Sprache festhalten: das Tonalitäts-Profil', 'WERKSTATT', '18 Min'],
      ['Website-Texte, die nicht nach KI klingen', 'WERKSTATT', '20 Min'],
      ['Anfragen in drei Minuten qualifizieren', 'WERKSTATT', '16 Min'],
      ['Bewertungen und Referenzen einholen', 'ÜBUNG', '14 Min'],
      ['Ein Rhythmus, den Sie halten können', 'ÜBUNG', '20 Min'],
      ['Was Chefsache bleibt', 'VIDEO', '10 Min'],
    ],
  },
  {
    n: '08', title: 'Kundenservice & vaiaconBot', level: 'PRAXIS', hours: '1 Std 23',
    nutzen: 'Der vaiaconBot beantwortet die zwanzig häufigsten Fragen rund um die Uhr. Ihr Telefon klingelt deutlich seltener für Auskünfte, die längst auf der Website stehen.',
    tile: 'Ein digitaler Mitarbeiter für die zwanzig häufigsten Fragen.',
    lead: 'Der vaiaconBot beantwortet, was sich täglich wiederholt — und gibt sauber an den Menschen ab, wenn es persönlich wird. Sie bauen ihn in dieser Werkstatt selbst.',
    bild: 'Bild: vaiaconBot am Telefon',
    img: 'assets/vaiacon-buerobot-phone.png',
    takeaways: ['Fragenkatalog (20 Fragen)', 'Übergabe-Regeln an den Menschen', 'Qualitäts-Check zum Mitlesen'],
    lessons: [
      ['Die zwanzig häufigsten Fragen sammeln', 'ÜBUNG', '14 Min'],
      ['Ein vaiaconBot für die häufigen Fragen', 'WERKSTATT', '24 Min'],
      ['Übergabe an den Menschen — sauber geregelt', 'WERKSTATT', '16 Min'],
      ['Telefonnotizen und Rückrufe', 'WERKSTATT', '14 Min'],
      ['Qualität prüfen: mitlesen und nachschärfen', 'ÜBUNG', '15 Min'],
    ],
  },
  {
    n: '09', title: 'Abläufe automatisieren', level: 'FORTGESCHRITTEN', hours: '2 Std 03',
    nutzen: 'Ein Ablauf, den Sie einmal bauen, arbeitet jede Woche weiter — typisch ein halber Arbeitstag pro Monat, den Sie zurückbekommen.',
    tile: 'Vom einzelnen Handgriff zum verlässlichen Ablauf.',
    lead: 'Für Betriebe, die den ersten Nutzen gesehen haben und jetzt Struktur wollen: beschreiben, bauen, verbinden, prüfen — inklusive Rückfallplan, wenn etwas nicht läuft.',
    bild: 'Bild: Werkstatt-Whiteboard mit Ablauf',
    img: 'assets/lernplan-09.png',
    takeaways: ['Prozess-Steckbrief', 'Ablauf-Bauplan', 'Rückfallplan (eine Seite)'],
    lessons: [
      ['Vom Handgriff zum Prozess: sauber beschreiben', 'WERKSTATT', '20 Min'],
      ['Der erste automatische Ablauf', 'WERKSTATT', '26 Min'],
      ['Verbindungen ohne Programmieren', 'WERKSTATT', '24 Min'],
      ['Daten sauber halten', 'WERKSTATT', '18 Min'],
      ['Wenn es schiefgeht: der Rückfallplan', 'WERKSTATT', '15 Min'],
      ['Aus einem Ablauf zehn machen', 'ÜBUNG', '20 Min'],
    ],
  },
  {
    n: '10', title: 'Zahlen & Entscheide', level: 'FÜHRUNG', hours: '1 Std 08',
    nutzen: 'Sie rechnen vor dem Kauf, ob sich ein Werkzeug lohnt — und stoppen Abos, die nichts bringen. Das sind schnell einige Hundert Franken im Jahr.',
    tile: 'Rechnen statt hoffen: Kosten, Nutzen, Quartals-Entscheid.',
    lead: 'Was bringt es wirklich? Sie rechnen Ihren eigenen Fall durch, vergleichen Lizenzen und entscheiden pro Quartal, was bleibt und was wieder verschwindet.',
    bild: 'Bild: Notizblock mit Zahlen',
    img: 'assets/lernplan-10.png',
    takeaways: ['Business-Case-Rechner', 'Lizenz-Vergleichsblatt', 'Quartals-Entscheid (Vorlage)'],
    lessons: [
      ['Kosten und Nutzen rechnen', 'ÜBUNG', '22 Min'],
      ['Angebote und Lizenzen vergleichen', 'VIDEO', '14 Min'],
      ['Wann sich Eigenbau lohnt — und wann nicht', 'VIDEO', '14 Min'],
      ['Der Quartals-Entscheid: was bleibt, was fliegt', 'ÜBUNG', '18 Min'],
    ],
  },
  {
    n: '11', title: 'Team & Verantwortung', level: 'FÜHRUNG', hours: '1 Std 17',
    nutzen: 'Ihre Mitarbeitenden nutzen KI nach klaren Regeln statt heimlich am eigenen Konto. Sie behalten die Kontrolle über Daten und Qualität.',
    tile: 'Regeln, Rollen und der Umgang mit Skepsis im Team.',
    lead: 'KI im Betrieb ist Führungsarbeit. Sie schreiben eine Richtlinie auf einer Seite, klären Rollen und Freigaben und nehmen die Mitarbeitenden mit, statt sie zu überfahren.',
    bild: 'Bild: Team im Pausenraum',
    img: 'assets/lernplan-11.png',
    takeaways: ['KI-Richtlinie auf einer Seite', 'Rollen- und Freigabe-Matrix', 'Schulungsplan fürs Team'],
    lessons: [
      ['Eine KI-Richtlinie auf einer Seite', 'WERKSTATT', '20 Min'],
      ['Mitarbeitende mitnehmen statt überfahren', 'VIDEO', '14 Min'],
      ['Wer darf was? Rollen und Freigaben', 'WERKSTATT', '16 Min'],
      ['Umgang mit Skepsis im Team', 'VIDEO', '12 Min'],
      ['KI-Kompetenz messen: der kleine Check', 'ÜBUNG', '15 Min'],
    ],
  },
  // Modul 12 «Advanced: Wie KI wirklich funktioniert» wurde am 08.09.2026
  // entfernt — es diente nur internen Zwecken. Die Kursseiten liegen weiterhin
  // unter academy/kurs/, sind aus der Academy aber nicht mehr verlinkt.
];
